### ISSUE TITLE
macOS notifications steal focus

### ISSUE THREAD

**Issue by tzapu** [blainesch/electron-notifier#12]
as the title says, there s a bit of an usability issue with this on macOS, it steals focus from whatever window is active when a notification is displayed.

no combination of flags yielded anything useful for me, but i am very much scratching the surface of all this stuff.

thank you for a lovely package

**Comment by bayleedev** [comment]
Fixed by #11

**Comment by tzapu** [comment]
thanks for adding the request. unfortunately, even with focusable false it still steals the focus on mac os
if i find anything more related to this, i ll post it here
cheers

**Comment by bayleedev** [comment]
It's not stealing focus for me. In the playbook I did a settimeout to open a notification in 2 seconds, then I started typing in the textarea and I could still type after it opened.

**Comment by tzapu** [comment]
not sure i understood the test exactly, but i probably have not explained myself correctly.

i type in another app altogether, like messages or slack on macOS and when the notification pops, the electron app that popped the notification gets focus so i can t continue writing in the prev app.

thanks
