### ISSUE TITLE
Shows blank popup on Windows 7

### ISSUE THREAD

**Issue by afriedma** [blainesch/electron-notifier#15]
Hi,

I ran the Playbook, the outline of the pop up shows us, but no content.  Could you please advise.

![image](https://cloud.githubusercontent.com/assets/22999195/22654683/9c1a1ef0-ec5b-11e6-81bb-2e6043d370a1.png)

**Comment by blainesch** [comment]
What do you mean you ran the playbook? The theme playbook is a web tool for showing off your theme. It shouldn't be used with Zazu.

Can you post in your `C:\Users\<YOUR_USER>\.zazurc.json` file?

**Comment by bayleedev** [comment]
This could be due to a flag in how we are initializing the playbook. If you open the chrome developer tools does it tell you about any errors?

**Comment by afriedma** [comment]
There are no errors. It just doesn't get rendered.

Just to give more context, I am using a classic theme for windows 7. 
Can it have anything to do with window initialization options, e. g. transparent?

My target app will be electron/angular2 app.  But I can reproduce it in playbook.

**Comment by afriedma** [comment]
I am running the playbook based on your documentation.

I don't see this file in the directory.  I posted more context on the issue.

Cheers, Alex

________________________________

**Comment by Nantris** [comment]
Runs on Windows 7 x64 Professional for me in my Electron application. At least it did a few weeks ago. Have not tried the newest version.

**Comment by afriedma** [comment]
Switch your theme to Windows Classic give it a try, you should be able to re-produce it.

![image](https://cloud.githubusercontent.com/assets/22999195/22693279/93822746-ed10-11e6-9897-73bd94f78d87.png)

![image](https://cloud.githubusercontent.com/assets/22999195/22694812/a3225260-ed16-11e6-8462-ecf81414aa55.png)

My guess it has something to do with transparent flag when window is created, but I don't know how to fix it.

**Comment by bayleedev** [comment]
The playbook doesn't have the transparent flag, just the notifications. Is your playbook working before you change that setting?

**Comment by afriedma** [comment]
I am sorry, I was referring to notifications, playbook app is fine, it works great.

The rectangular spots in bottom right corner of the screen shot, that's how notifications show up, sorry if I wasn't clear.

**Comment by bayleedev** [comment]
Then yes, the issue is some windows versions have issues with the transparency. To fix this I'd disable transparency on windows.

Something like:

~~~ javascript
const isWindows = process.platform === 'win32'
// ...
  transparent: !isWindows,
// ...
~~~

Somewhere around [here](https://github.com/blainesch/electron-notifications/blob/e1fecff3129a9eb49640849a630b19b36b3b2255/lib/notifier.js#L41)

Do you mind submitting a pr?

**Comment by afriedma** [comment]
That worked, but that makes the pop up look weird, see screen shot below.

![image](https://cloud.githubusercontent.com/assets/22999195/22713964/784e0e5c-ed58-11e6-86f5-502c5fa99cc9.png)

**Comment by bayleedev** [comment]
We might have to change some css to get this to work correctly.

**Comment by afriedma** [comment]
Do you know what needs to be changed?  I can submit a pr.  Also, I think, this will fix showing notification on electron renderer process, currently it doesn't work. I get the same blank notification.

**Comment by bayleedev** [comment]
Yes, we'd need to remove the drop shadow and border from the css and rely on the OS to implement that. We'd lose rounded corners, but at least it would work consistently.

**Comment by afriedma** [comment]
I removed border-radius and box-shadow from #notification in css.
There is still white background and notification is inside it, doesn't look good. 

Any other ideas?

![image](https://cloud.githubusercontent.com/assets/22999195/22894101/de324224-f1e5-11e6-9457-0da117a1da07.png)

**Comment by bayleedev** [comment]
Can you make a pr with what you do have and I'll try and add a css commit?

**Comment by afriedma** [comment]
I submitted a pull request, are you planning a release with fixes soon?

**Comment by bayleedev** [comment]
I'll look at it this weekend.

**Comment by afriedma** [comment]
Hi,

Any luck?

**Comment by afriedma** [comment]
Dark theme looks sweet, but there is a white border around the notification, see the image.
![image](https://cloud.githubusercontent.com/assets/22999195/23463457/91592f18-fe5f-11e6-9601-9e6ff58990d7.png)
