### ISSUE TITLE
Uncaught Exception on click event

### ISSUE THREAD

**Issue by afriedma** [blainesch/electron-notifier#16]
I get the exception below, with this code

```
ipcMain.on('asynchronous-message', (event, arg) => {
    console.log(arg);

    var notification = notifier.notify('Alert', {
        message: 'Invalid System Detected.',
        icon: 'https://docs.nativescript.org/img/cli-getting-started/angular/chapter0/Angular_logo.png',
        //duration: 5000,
        buttons: ['Dismiss', 'Snooze'],
    });

    notification.on('buttonClicked', (text, index) => {
        notification.close();
        alert('You clicked "' + text + '" at index ' + index);
    });

});
```
![image](https://cloud.githubusercontent.com/assets/22999195/22664556/34959880-ec7f-11e6-90f7-4120b24a6a40.png)

**Comment by bayleedev** [comment]
I believe all click events will destroy the notification so `notification.close();` might be the issue and could be removed.

**Comment by afriedma** [comment]
That was it, thank you very much for prompt reply.

**Comment by Nantris** [comment]
Click events don't close the notification for me?

I get this same error but it seems like I need `notification.close()` or the notification does not leave.
