### ISSUE TITLE
Shows blank pop uop on Ubuntu 16.04

### ISSUE THREAD

**Issue by faisal00813** [blainesch/electron-notifier#18]
![image](https://cloud.githubusercontent.com/assets/2932262/23009710/794e0104-f43d-11e6-8217-af825aa37342.png)

Shows up blank on Ubuntu.

[Tried setting `windowOptions.transperancy` to false](https://github.com/blainesch/electron-notifications/blob/e1fecff3129a9eb49640849a630b19b36b3b2255/lib/notifier.js#L41) . No Success

**Comment by bayleedev** [comment]
Thanks for reporting!
