### ISSUE TITLE
update package on npm

### ISSUE THREAD

**Issue by hanayik** [blainesch/electron-notifier#20]
@blainesch would it be possible for you to publish an updated version on npm soon? I love this module, and have it implemented in my app, but it's currently commented out because I'd like to use your module rather than publish my own on npm just to solve my fix from earlier #19 . If there was a way for me to do it for you I would have. I hate having to put this on your shoulders so quickly.

**Comment by bayleedev** [comment]
Published v0.1.6

**Comment by hanayik** [comment]
Awesome! Thanks for handling everything so quickly!
