### ISSUE TITLE
Notifications cannot run when packaged with electron-builder

### ISSUE THREAD

**Issue by Nantris** [blainesch/electron-notifier#21]
This could be due to a different issue, but this is my best deduction. The windows simply do not show up, but I can tell they are trying to because I lose focus on the window when they attempt to create.

I have set up an example here: https://github.com/Slapbox/electron-notification-demo

In `App\Components\Home.js` I generate a notification at startup and then every 25 seconds.
```
ipcRenderer.send('reminders');

setInterval(function() {
  console.log("Attempting to create notification");
  ipcRenderer.send('reminders');
}, 25000)
```

in `App\Main.development.js` 
```
  ipcMain.on('reminders', (event, arg) => {
    console.log("Attempting to create notification");
    notifier.notify("Test");
  }); 
```

Run in development with: `npm run dev` and you can see they run fine.

Run the exe `release\win-unpacked\ElectronReact.exe` to run a packaged version. On right click you can `inspect element` to view the developer tools, but I don't know of any way to debug the main process unfortunately.

Any ideas what may cause this? This is an excellent package. It's a real bummer that it's not working so far in a production build. Thanks for any insight you can provide.

**Comment by bayleedev** [comment]
I have no idea what could be causing this, thank you for reporting the issue!

**Comment by Nantris** [comment]
Can you explain in 2-3 sentences how/where in the package notifications are generated? I will try to investigate further.

**Comment by bayleedev** [comment]
@Slapbox we create new browser windows in this file:

https://github.com/blainesch/electron-notifications/blob/master/lib/notifier.js

**Comment by Nantris** [comment]
The newest version with `Electron 1.6.1` and `Electron-builder 12.3.1` does create windows. Huzzah!

Unfortunately they're empty white windows. I'm guessing that some required file is not being loaded.

**Comment by Nantris** [comment]
Okay finally got an error message:

`Not allowed to load local resource: file:///C:/Projects/MyApp/release/win-unpacked/resources/app.asar/assets/notification.html`

Extracting the app.asar shows that this file is not being included by `electron-builder` so I will have to determine how to get it and the corresponding CSS file in the same directory included.

**Comment by Nantris** [comment]
I have literally no idea how to remedy this..

I think that the `HtmlWebpackPlugin` is needed to import the `notification.html` but I can't find any working configuration, and if this is the right path, it would only be a first step in resolving the issue most likely.

**Comment by bayleedev** [comment]
@Slapbox do you have a repo case online I can download?

We don't currently compile with webpack, but we could try and compile it to include the html file inline. This could help, but we might have to change how this works.

It could also be useful to try and list all the files necessary in the package.json?
https://docs.npmjs.com/files/package.json#files

**Comment by Nantris** [comment]
I did try a few things to bring the files in in the package.json and in my webpack.config files, but no luck. I have no doubt there is a way to do it, but I don't know what it is and help material/questions on this particular type of issue seem to be nearly impossible to find, though perhaps I simply don't know what to search for.

I've put together a repo to demonstrate the issue. You can view the repo here: https://github.com/Slapbox/electron-notification-demo

You can download just the contents of https://github.com/Slapbox/electron-notification-demo/tree/master/release/win-unpacked and run ElectronReact.exe. The application will create a notification window on startup. Developer tools should be available for both the main application and for the `Electron-Notifications` window that is created.

The notification is generated in the Home.js file around line 9. It should last for an hour before closing.

If you need to generate another notification window you can do so with `notifier('reminders');` in the console.

Thanks very much for taking a look @blainesch!

**Comment by Nantris** [comment]
React-Electron-Boilerplate works just fine with this repo. You must add the dependency to your SECOND `package.json`, located within the `app` folder.
