### ISSUE TITLE
Problem build app

### ISSUE THREAD

**Issue by candidoalberto** [blainesch/electron-notifier#3]
Hello @blainesch , thanks for the plugin.

it works well when the development environment .

But when build app , gives the following error:

![teste](https://cloud.githubusercontent.com/assets/2072495/17827053/91afd674-664d-11e6-807e-c3acd52083e2.png)

**Comment by bayleedev** [comment]
What's the output of `process.versions` ?

**Comment by candidoalbertosilva** [comment]
![processversion](https://cloud.githubusercontent.com/assets/20017087/17832786/cb141e40-66e1-11e6-8673-defcefb23e59.png)

**Comment by bayleedev** [comment]
The [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) I'm doing isn't available until Chrome 49, and you're using 47. I'd recommend upgrading your electron version.

Alternatively, if you want to downgrade the es6 in this repo to es5, I'll accept the pull request.
