### ISSUE TITLE
CSS issue - white borders.

### ISSUE THREAD

**Issue by simon-holm** [blainesch/electron-notifier#30]
Hello!

Thanks for this package!

I am having a small issue with the CSS. I am getting a white border at the bottom of the notification. Is there any way of injecting styles without going into the npm directory?

in notification.css  i changed
#notification {
  height: 80px  --> 82px

and the white bottom border is gone.

**Comment by bayleedev** [comment]
Can you submit a pr?

**Comment by simon-holm** [comment]
Just got back from a few days vacay. I'll have a look at it and submit a pr later on!

*edit*
I dont seem to get the same behaviour on my other computer. So could have been something on my end causing the extra whitespace.

**Comment by bayleedev** [comment]
Sweet! Thanks for letting me know!
