### ISSUE TITLE
If there is more than one notification, close button doesn`t work

### ISSUE THREAD

**Issue by ue** [blainesch/electron-notifier#31]
for example we have 5 notification at the same time, and than just click to Close button is mean; 
```
else if(text == "Close") {
      notification.close() 
 } 
```
after than if click another notification, it`s nothing happen

**Comment by bayleedev** [comment]
Thanks for reporting it!

**Comment by ue** [comment]
@blainesch Hi I`m so sory for this issue. Thats my fault. I used ``` let ```  instead of  const. So there is no problem. You can close.

**Comment by bayleedev** [comment]
Thanks!
