### ISSUE TITLE
Does not work on windows 8

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [blainesch/electron-notifier#9]
Hi

I am trying your sample code on windows 8.
I does not seem to work. I works on windows 10 though.

**Comment by bayleedev** [comment]
I'll take a look. Thank you!

**Comment by tzapu** [comment]
hi, ran into this as well, it seems related to transparent: true

will post when/if we find a suitable solution

cheers

**Comment by tzapu** [comment]
hi, it seems it s a combination of flags that make this not appear on win 8
i've added
`resizeable :false`
and removed
`minimizable: false, maximizable: false,`

and it seems ok on windows 8. did not test on other systems yet, but it shouldn t be a problem. will test win 10 and macos just to be sure.

would you prefer a pull request after?

cheers

**Comment by tzapu** [comment]
in our tests it seems to work both on win 10 and macOS (except this which is still an issue: https://github.com/blainesch/electron-notifications/issues/12 )
